/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DemoRouteImport } from './routes/demo'
import { Route as DashboardRouteRouteImport } from './routes/dashboard/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as ApiIngestRouteImport } from './routes/api/ingest'
import { Route as DashboardProjectIdRouteRouteImport } from './routes/dashboard/$projectId/route'
import { Route as DashboardProjectIdSetupRouteImport } from './routes/dashboard/$projectId/setup'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoRoute = DemoRouteImport.update({
  id: '/demo',
  path: '/demo',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRouteRoute = DashboardRouteRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const ApiIngestRoute = ApiIngestRouteImport.update({
  id: '/api/ingest',
  path: '/api/ingest',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardProjectIdRouteRoute = DashboardProjectIdRouteRouteImport.update({
  id: '/$projectId',
  path: '/$projectId',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardProjectIdSetupRoute = DashboardProjectIdSetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => DashboardProjectIdRouteRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/demo': typeof DemoRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/dashboard/$projectId': typeof DashboardProjectIdRouteRouteWithChildren
  '/api/ingest': typeof ApiIngestRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/dashboard/$projectId/setup': typeof DashboardProjectIdSetupRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/demo': typeof DemoRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/dashboard/$projectId': typeof DashboardProjectIdRouteRouteWithChildren
  '/api/ingest': typeof ApiIngestRoute
  '/dashboard': typeof DashboardIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/dashboard/$projectId/setup': typeof DashboardProjectIdSetupRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/demo': typeof DemoRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/dashboard/$projectId': typeof DashboardProjectIdRouteRouteWithChildren
  '/api/ingest': typeof ApiIngestRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/dashboard/$projectId/setup': typeof DashboardProjectIdSetupRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/demo'
    | '/login'
    | '/register'
    | '/dashboard/$projectId'
    | '/api/ingest'
    | '/dashboard/'
    | '/api/auth/$'
    | '/dashboard/$projectId/setup'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/demo'
    | '/login'
    | '/register'
    | '/dashboard/$projectId'
    | '/api/ingest'
    | '/dashboard'
    | '/api/auth/$'
    | '/dashboard/$projectId/setup'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/demo'
    | '/login'
    | '/register'
    | '/dashboard/$projectId'
    | '/api/ingest'
    | '/dashboard/'
    | '/api/auth/$'
    | '/dashboard/$projectId/setup'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRouteRoute: typeof DashboardRouteRouteWithChildren
  DemoRoute: typeof DemoRoute
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  ApiIngestRoute: typeof ApiIngestRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo': {
      id: '/demo'
      path: '/demo'
      fullPath: '/demo'
      preLoaderRoute: typeof DemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/api/ingest': {
      id: '/api/ingest'
      path: '/api/ingest'
      fullPath: '/api/ingest'
      preLoaderRoute: typeof ApiIngestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/$projectId': {
      id: '/dashboard/$projectId'
      path: '/$projectId'
      fullPath: '/dashboard/$projectId'
      preLoaderRoute: typeof DashboardProjectIdRouteRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/$projectId/setup': {
      id: '/dashboard/$projectId/setup'
      path: '/setup'
      fullPath: '/dashboard/$projectId/setup'
      preLoaderRoute: typeof DashboardProjectIdSetupRouteImport
      parentRoute: typeof DashboardProjectIdRouteRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface DashboardProjectIdRouteRouteChildren {
  DashboardProjectIdSetupRoute: typeof DashboardProjectIdSetupRoute
}

const DashboardProjectIdRouteRouteChildren: DashboardProjectIdRouteRouteChildren =
  {
    DashboardProjectIdSetupRoute: DashboardProjectIdSetupRoute,
  }

const DashboardProjectIdRouteRouteWithChildren =
  DashboardProjectIdRouteRoute._addFileChildren(
    DashboardProjectIdRouteRouteChildren,
  )

interface DashboardRouteRouteChildren {
  DashboardProjectIdRouteRoute: typeof DashboardProjectIdRouteRouteWithChildren
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteRouteChildren: DashboardRouteRouteChildren = {
  DashboardProjectIdRouteRoute: DashboardProjectIdRouteRouteWithChildren,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteRouteWithChildren = DashboardRouteRoute._addFileChildren(
  DashboardRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRouteRoute: DashboardRouteRouteWithChildren,
  DemoRoute: DemoRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  ApiIngestRoute: ApiIngestRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
